INSERT INTO customers
    VALUES (7, 'Muffy', 24, 'Indore', 10000.00 );
    INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (2, 'Van Ha', 25, 'Ha Noi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (3, 'Vu Bang', 23, 'Vinh', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (4, 'Thu Minh', 25, 'Ha Noi', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (5, 'Hai An', 27, 'Ha Noi', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)

    VALUES (6, 'Hoang', 22, 'Ha Noi', 4500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
    select * from customers;